import React from 'react'
import Head from 'next/head'
import dynamic from 'next/dynamic'
import parse from 'html-react-parser'

import features from '@docs/general/features.md'

const FeaturePage = dynamic(() => import('@page-components/FeaturePage'), {
  ssr: false,
  loading: () => <p>Loading...</p>
})

export default function Home() {
  return (
    <>
      <Head>
        <title>NextJS Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Welcome to Next.js!</h1>
      <FeaturePage>{parse(`${features}`)}</FeaturePage>
    </>
  )
}
